#!/bin/bash
# pf setup script for macOS transparent proxy
# This script configures pf rules for transparent proxy

set -e

# Configuration
PROXY_PORT=${PROXY_PORT:-12345}
PROXY_INTERFACE=${PROXY_INTERFACE:-lo0}
EXTERNAL_INTERFACE=${EXTERNAL_INTERFACE:-en0}
PF_ANCHOR="com.netproxy"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "Please run as root (sudo)"
        exit 1
    fi
}

# Backup current pf configuration
backup_pf() {
    local backup_file="/tmp/pf.conf.backup.$(date +%Y%m%d%H%M%S)"
    if [ -f /etc/pf.conf ]; then
        cp /etc/pf.conf "$backup_file"
        log_info "Backed up pf.conf to $backup_file"
    fi
}

# Generate pf rules
generate_rules() {
    cat << EOF
# NetProxy transparent proxy rules
# Generated by pf_setup.sh

# Skip localhost
set skip on lo0

# Normalize packets
scrub in all

# NAT/RDR rules for transparent proxy
rdr pass on ${EXTERNAL_INTERFACE} inet proto tcp from any to any -> 127.0.0.1 port ${PROXY_PORT}

# Allow all traffic (adjust as needed)
pass in all
pass out all

# Log blocked packets (optional)
# block log all
EOF
}

# Setup pf anchor
setup_anchor() {
    log_info "Setting up pf anchor ${PF_ANCHOR}..."
    
    # Create anchor rules file
    local anchor_file="/etc/pf.anchors/${PF_ANCHOR}"
    mkdir -p /etc/pf.anchors
    
    cat > "$anchor_file" << EOF
# NetProxy transparent proxy anchor rules

# Redirect TCP traffic to proxy
rdr pass on ${EXTERNAL_INTERFACE} inet proto tcp from any to any port 1:65535 -> 127.0.0.1 port ${PROXY_PORT}

# Pass all other traffic
pass in all
pass out all
EOF
    
    log_info "Anchor rules written to $anchor_file"
}

# Add anchor to main pf.conf
add_anchor_to_pf() {
    log_info "Adding anchor to pf.conf..."
    
    local pf_conf="/etc/pf.conf"
    
    # Check if anchor already exists
    if grep -q "anchor \"${PF_ANCHOR}\"" "$pf_conf" 2>/dev/null; then
        log_warn "Anchor already exists in pf.conf"
        return
    fi
    
    # Backup original
    backup_pf
    
    # Add anchor reference
    cat >> "$pf_conf" << EOF

# NetProxy transparent proxy anchor
rdr-anchor "${PF_ANCHOR}"
anchor "${PF_ANCHOR}"
load anchor "${PF_ANCHOR}" from "/etc/pf.anchors/${PF_ANCHOR}"
EOF
    
    log_info "Anchor added to pf.conf"
}

# Enable pf
enable_pf() {
    log_info "Enabling pf..."
    
    # Load the rules
    pfctl -f /etc/pf.conf 2>/dev/null || true
    
    # Enable pf
    pfctl -e 2>/dev/null || true
    
    log_info "pf enabled"
}

# Disable pf
disable_pf() {
    log_info "Disabling pf..."
    pfctl -d 2>/dev/null || true
    log_info "pf disabled"
}

# Reload pf rules
reload_pf() {
    log_info "Reloading pf rules..."
    pfctl -f /etc/pf.conf
    log_info "pf rules reloaded"
}

# Setup IP forwarding
setup_forwarding() {
    log_info "Enabling IP forwarding..."
    sysctl -w net.inet.ip.forwarding=1 > /dev/null
    log_info "IP forwarding enabled"
}

# Clean up rules
cleanup() {
    log_info "Cleaning up NetProxy pf rules..."
    
    # Remove anchor file
    rm -f "/etc/pf.anchors/${PF_ANCHOR}"
    
    # Remove anchor from pf.conf
    if [ -f /etc/pf.conf ]; then
        # Create temp file without our rules
        grep -v "NetProxy transparent proxy" /etc/pf.conf | \
        grep -v "anchor \"${PF_ANCHOR}\"" | \
        grep -v "rdr-anchor \"${PF_ANCHOR}\"" | \
        grep -v "load anchor \"${PF_ANCHOR}\"" > /tmp/pf.conf.clean
        
        mv /tmp/pf.conf.clean /etc/pf.conf
    fi
    
    # Reload pf
    pfctl -f /etc/pf.conf 2>/dev/null || true
    
    log_info "Cleanup completed"
}

# Show status
status() {
    echo "=== pf Status ==="
    echo ""
    echo "pf enabled:"
    pfctl -s info 2>/dev/null | head -5 || echo "  pf not running"
    echo ""
    echo "Current rules:"
    pfctl -s rules 2>/dev/null | head -20 || echo "  No rules loaded"
    echo ""
    echo "NAT/RDR rules:"
    pfctl -s nat 2>/dev/null || echo "  No NAT rules"
    echo ""
    echo "Anchor ${PF_ANCHOR}:"
    pfctl -a "${PF_ANCHOR}" -s rules 2>/dev/null || echo "  Anchor not loaded"
}

# Simple setup without anchor (for testing)
simple_setup() {
    log_info "Setting up simple pf redirect rules..."
    
    # Create simple rules
    cat > /tmp/netproxy_pf.conf << EOF
# Simple NetProxy transparent proxy rules

# Redirect all TCP traffic on external interface to proxy
rdr on ${EXTERNAL_INTERFACE} inet proto tcp from any to any -> 127.0.0.1 port ${PROXY_PORT}

# Pass all traffic
pass in all
pass out all
EOF
    
    # Load rules
    pfctl -f /tmp/netproxy_pf.conf
    pfctl -e 2>/dev/null || true
    
    log_info "Simple pf rules loaded"
    log_info "Proxy should listen on 127.0.0.1:${PROXY_PORT}"
}

# Print usage
usage() {
    echo "Usage: $0 {setup|simple|cleanup|status|enable|disable|reload}"
    echo ""
    echo "Commands:"
    echo "  setup   - Configure pf anchor for transparent proxy"
    echo "  simple  - Simple setup without anchor (for testing)"
    echo "  cleanup - Remove all NetProxy pf rules"
    echo "  status  - Show current pf configuration"
    echo "  enable  - Enable pf"
    echo "  disable - Disable pf"
    echo "  reload  - Reload pf rules"
    echo ""
    echo "Environment Variables:"
    echo "  PROXY_PORT          - Proxy listening port (default: 12345)"
    echo "  PROXY_INTERFACE     - Loopback interface (default: lo0)"
    echo "  EXTERNAL_INTERFACE  - External interface (default: en0)"
    echo ""
    echo "Example:"
    echo "  sudo PROXY_PORT=12345 EXTERNAL_INTERFACE=en0 $0 setup"
}

# Main
main() {
    check_root
    
    case "$1" in
        setup)
            setup_forwarding
            setup_anchor
            add_anchor_to_pf
            enable_pf
            log_info "pf setup completed successfully"
            log_info "Proxy should listen on 127.0.0.1:${PROXY_PORT}"
            ;;
        simple)
            setup_forwarding
            simple_setup
            ;;
        cleanup)
            cleanup
            ;;
        status)
            status
            ;;
        enable)
            enable_pf
            ;;
        disable)
            disable_pf
            ;;
        reload)
            reload_pf
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "$@"
